name: Deploy to Azure

on:
  push:
    branches:
      - main # Change la branche si nécessaire

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout le code source
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Connexion à Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 3. Configuration de Docker pour ACR
    - name: Log in to ACR
      run: |
        echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    # 4. Construction et Push de l'image Docker vers ACR
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/weather-app:latest .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/weather-app:latest

    # 5. Déploiement sur Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: weather-app # Remplace par le nom de ton Web App
        images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/weather-app:latest
