name: Deploy Weather App to Azure

on:
  push:
    branches:
      - main  # Déclenche ll'action sur un push vers la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_NAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image
      run: |
         TAG="v$(date +'%Y%m%d%H%M%S')"
    echo "Tagging the image with version: $TAG"
    echo "ACR Name: ${{ secrets.ACR_NAME }}"
    echo "Image Name: ${{ secrets.IMAGE_NAME }}"
    echo "Tag: $TAG"
    docker build -t "${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:$TAG" .

    - name: Push Docker image to ACR
      run: |
        echo "Pushing Docker image to ACR..."
        echo "Pushing image: ${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:$TAG"
        docker push "${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:$TAG"

    - name: Azure Web App deployment
      run: |
        echo "Getting ACR password..."
        ACR_PASSWORD=$(az acr credential show --name ${{ secrets.ACR_NAME }} --query "passwords[0].value" -o tsv)
        echo "Deploying to Azure Web App..."
        az webapp config container set \
          --name ${{ secrets.WEB_APP_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --docker-custom-image-name "${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:$TAG" \
          --docker-registry-server-url "https://${{ secrets.ACR_NAME }}.azurecr.io" \
          --docker-registry-server-user ${{ secrets.ACR_NAME }} \
          --docker-registry-server-password $ACR_PASSWORD

    - name: Deployment completed
      run: echo "Deployment completed with version $TAG"
